### ISSUE TITLE
[Bug] Missing most source tables

### ISSUE THREAD

**Issue by jaredx435k2d0** [fivetran/dbt_netsuite_source#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

We have 1388 tables being synced by our NetSuite2 connector.

However, my stg_netsuite_suiteanalytics schema has only 40 views.

### Expected behavior

I expected to see all of those output in the schema I designated for this package in my `dbt_project.yml`:
```
  netsuite_source:
    +schema: stg_netsuite_suiteanalytics
    +materialized: view
```

I'd prefer to not have to replicate the remainder of them manually. How do I get the package to bring in all of my source tables?

### dbt Project configurations

```
models:

  netsuite:
    +schema: netsuite_suiteanalytics
  netsuite_source:
    +schema: stg_netsuite_suiteanalytics
    +materialized: view

vars:

  # fivetran/netsuite package variables
  netsuite_database: [my_db_name_redacted]
  netsuite_schema: [my_schema_name_redacted]
  netsuite_data_model: netsuite2 #netsuite by default
  netsuite2__multibook_accounting_enabled: false
  netsuite2__using_vendor_categories: true
```

### Package versions

packages:
  - package: dbt-labs/codegen
    version: 0.9.0

  - package: fivetran/zendesk
    version: [">=0.10.0", "<0.11.0"]

  - package: fivetran/netsuite
    version: [">=0.7.0", "<0.8.0"]

### What database are you using dbt with?

snowflake

### dbt Version

```
dbt --version
Core:
  - installed: 1.4.5
  - latest:    1.4.5 - Up to date!

Plugins:
  - snowflake: 1.4.2 - Up to date!
```

We are using Fivetran dbt Transformations. We have no deployment.yml file because we are using Scheduled with Fivetran. The dbt Core version we're using there is 1.3.2

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.
